In [1]:
from sklearn.datasets import load_boston

In [2]:
import os
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline

In [3]:
boston = load_boston()

In [4]:
X = boston['data']
Y = boston['target']

X_names = boston['feature_names']

total_data = np.concatenate([X,Y.reshape(-1,1)], axis = 1)
total_feature_names = np.append(X_names, 'Y')

total_data = pd.DataFrame(total_data, columns = total_feature_names)

total_data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT     Y  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

In [5]:
num_train = round(X.shape[0]*0.7)

# Train Data와 Test Data로 나누기(70:30 비율로)
Train_X = total_data.iloc[:num_train, :-1]
Test_X = total_data.iloc[num_train:, :-1]

Train_Y = total_data.iloc[:num_train, -1]
Test_Y = total_data.iloc[num_train:, -1]

In [6]:
from sklearn.neighbors import KNeighborsRegressor as knn

In [7]:
KNN = knn() # k=5일 때(Default)

In [8]:
KNN.fit(Train_X, Train_Y)

KNeighborsRegressor()

In [9]:
pred = KNN.predict(Test_X)

In [10]:
pred

array([26.78, 28.58, 18.34, 16.98, 17.48, 16.36, 18.78, 18.34, 18.78,
       18.34, 18.34, 18.34, 18.12, 14.74, 19.38, 18.78, 19.56, 18.34,
       18.34, 15.68, 15.68, 18.56, 18.34, 16.48, 16.48, 16.48, 17.74,
       16.48, 16.48, 16.48, 18.12, 15.68, 15.74, 14.98, 16.4 , 16.48,
       17.06, 18.34, 15.74, 17.74, 17.74, 16.72, 17.42, 16.86, 15.74,
       17.8 , 15.74, 17.42, 18.34, 17.74, 17.8 , 15.8 , 18.34, 19.6 ,
       18.12, 18.76, 15.34, 15.34, 15.34, 18.76, 15.34, 15.34, 15.34,
       14.74, 15.34, 15.34, 18.12, 18.12, 18.12, 15.34, 15.34, 15.34,
       15.34, 15.34, 15.34, 15.34, 15.34, 15.34, 14.74, 14.74, 14.74,
       14.74, 15.34, 15.34, 15.34, 16.48, 15.34, 16.16, 17.98, 17.96,
       19.74, 15.34, 18.12, 18.92, 17.42, 18.12, 15.34, 18.34, 16.98,
       18.34, 15.34, 15.34, 15.34, 15.34, 18.12, 17.48, 18.12, 16.98,
       17.48, 18.46, 16.36, 18.96, 15.34, 19.6 , 18.34, 16.36, 17.36,
       17.22, 16.36, 18.34, 18.34, 18.12, 17.06, 18.34, 18.34, 18.78,
       17.48, 17.48,

In [11]:
from sklearn.metrics import mean_absolute_percentage_error as MAPE

In [12]:
MAPE(Test_Y, pred)*100

39.750707963969774

# k 값을 변경해보자!

In [13]:
KNN2 = knn(n_neighbors=1)
KNN3 = knn(n_neighbors = 100)

In [14]:
KNN2.fit(Train_X, Train_Y)
KNN3.fit(Train_X, Train_Y)

KNeighborsRegressor(n_neighbors=100)

In [15]:
pred2 = KNN2.predict(Test_X)

In [16]:
pred2

array([23.5, 23.5, 18.9, 18.9, 18.9, 18.9, 18.9, 18.9, 18.9, 18.9, 18.9,
       18.9, 18.9, 15.6, 18.9, 18.9, 18.9, 18.9, 18.9, 18.9, 18.9, 18.9,
       18.9, 18.9, 18.9, 18.9, 18.9, 18.9, 18.9, 18.9, 15.6, 18.9, 18.9,
       18.9, 18.9, 18.9, 18.9, 18.9, 18.9, 18.9, 18.9, 18.9, 18.9, 18.9,
       18.9, 18.9, 18.9, 18.9, 18.9, 18.9, 18.9, 18.9, 18.9, 18.9, 18.9,
       15.6, 13.1, 13.1, 13.1, 15.6, 13.1, 13.1, 15.6, 13.1, 13.1, 15.6,
       18.9, 18.9, 15.6, 15.6, 15.6, 13.1, 15.6, 15.6, 15.6, 13.1, 15.6,
       13.1, 15.6, 13.1, 13.1, 13.1, 13.1, 13.1, 15.6, 18.9, 18.9, 18.9,
       18.9, 18.9, 15.6, 13.1, 18.9, 18.9, 18.9, 15.6, 15.6, 18.9, 18.9,
       18.9, 13.1, 15.6, 15.6, 15.6, 15.6, 18.9, 15.6, 18.9, 18.9, 18.9,
       18.9, 18.9, 15.6, 18.9, 18.9, 18.9, 18.9, 18.9, 18.9, 18.9, 18.9,
       15.6, 18.9, 18.9, 18.9, 18.9, 18.9, 18.9, 18.9, 18.9, 18.9, 18.9,
       18.9, 18.9, 18.9, 18.9, 18.9, 18.9, 18.9, 21.7, 20.3, 20.3, 26.5,
       26.5, 26.5, 26.5, 27.5, 22.6, 22. , 23. , 23

In [17]:
MAPE(Test_Y, pred2)*100

43.033003679300094

In [18]:
# 만약, Train_X로 학습하면 어떻게 될까?
Train_pred1 = KNN.predict(Train_X)
Train_pred2 = KNN2.predict(Train_X)
Train_pred3 = KNN3.predict(Train_X)

In [19]:
print("Train_pred1: %.2f%%"%(MAPE(Train_Y, Train_pred1)*100))
print("Train_pred2: %.2f%%"%(MAPE(Train_Y, Train_pred2)*100))
print("Train_pred3: %.2f%%"%(MAPE(Train_Y, Train_pred3)*100))

Train_pred1: 13.94%
Train_pred2: 0.00%
Train_pred3: 23.26%


# Validation 데이터 추가

In [20]:
num_temp = round(total_data.shape[0]*0.7)

# Train Data와 Test Data, Validation으로 나누기
TEMP_X = total_data.iloc[:num_temp, :-1]
TEMP_Y = total_data.iloc[:num_temp, -1]

true_num_train = round(TEMP_X.shape[0]*0.7)

train_X = TEMP_X.iloc[:true_num_train]
vali_X = TEMP_X.iloc[true_num_train: , :]

train_Y = TEMP_Y.iloc[:true_num_train]
vali_Y = TEMP_Y.iloc[true_num_train:]

test_X = total_data.iloc[num_temp:, :-1]
test_Y = total_data.iloc[num_temp:, -1]

## Validation Data를 이용하여 최적의 K값을 찾아보자!

In [21]:
select_k = np.array(range(1,21,1))

In [23]:
obs_MAPE = []

# 반복적으로 학습을 진행함!
for k in select_k:
    new_KNN = knn(n_neighbors = k)
    
    new_KNN.fit(train_X, train_Y)
    validation_pred = new_KNN.predict(vali_X)
    
    validation_MAPE = MAPE(vali_Y, validation_pred)
    obs_MAPE.append(validation_MAPE)

# 이걸 해결 하자..? (해결 완료)

In [24]:
best_res = np.where(obs_MAPE == min(obs_MAPE))[0][0]

In [27]:
select_k

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [26]:
best_res

17

In [25]:
select_k[best_res]

18

In [28]:
basic_knn = knn()

In [29]:
basic_knn.fit(train_X, train_Y)

KNeighborsRegressor()

In [30]:
test_pred_basic = basic_knn.predict(Test_X)

In [31]:
best_k = select_k[best_res]

In [32]:
best_knn = knn(n_neighbors = best_k)

In [33]:
best_knn.fit(train_X, train_Y)

KNeighborsRegressor(n_neighbors=18)

In [34]:
test_pred = best_knn.predict(Test_X)

In [35]:
print(MAPE(Test_Y, test_pred)*100)
print(MAPE(Test_Y, test_pred_basic)*100)

47.057455761423526
39.99301690771256
